export const schemas = {
	Error: {
		type: "object",
		required: ["error"],
		properties: {
			error: { type: "string" },
		},
	},
	CustomMetricConfig: {
		type: "object",
		required: ["id", "name"],
		properties: {
			id: { type: "string", description: "Unique identifier for the metric", example: "connections" },
			name: { type: "string", description: "Human-readable display name", example: "Active Connections" },
			unit: { type: "string", description: "Unit of measurement", example: "conn" },
		},
	},
	CustomMetricData: {
		type: "object",
		required: ["config"],
		properties: {
			config: { $ref: "#/components/schemas/CustomMetricConfig" },
			value: { type: "number", description: "Current value of the metric", example: 150 },
		},
	},
	StatusData: {
		type: "object",
		required: ["id", "type", "name", "status", "latency", "uptime1h", "uptime24h", "uptime7d", "uptime30d", "uptime90d", "uptime365d"],
		properties: {
			id: { type: "string", example: "api-prod" },
			type: { type: "string", enum: ["monitor", "group"], example: "monitor" },
			name: { type: "string", example: "Production API" },
			status: { type: "string", enum: ["up", "down", "degraded"], example: "up" },
			latency: { type: "number", description: "Latest measured latency in milliseconds", example: 42 },
			lastCheck: { type: "string", format: "date-time", description: "Timestamp of the last check" },
			firstPulse: { type: "string", format: "date-time", description: "Timestamp of the first received pulse" },
			uptime1h: { type: "number", description: "1-hour uptime percentage", example: 100 },
			uptime24h: { type: "number", description: "24-hour uptime percentage", example: 100 },
			uptime7d: { type: "number", description: "7-day uptime percentage", example: 99.95 },
			uptime30d: { type: "number", description: "30-day uptime percentage", example: 99.98 },
			uptime90d: { type: "number", description: "90-day uptime percentage", example: 99.92 },
			uptime365d: { type: "number", description: "365-day uptime percentage", example: 99.95 },
			children: {
				type: "array",
				description: "Child status data (only for groups)",
				items: { $ref: "#/components/schemas/StatusData" },
			},
			custom1: { $ref: "#/components/schemas/CustomMetricData" },
			custom2: { $ref: "#/components/schemas/CustomMetricData" },
			custom3: { $ref: "#/components/schemas/CustomMetricData" },
		},
	},
	HistoryRecord: {
		type: "object",
		required: ["timestamp", "uptime"],
		properties: {
			timestamp: { type: "string", format: "date-time", example: "2025-01-15T10:00:00Z" },
			uptime: { type: "number", description: "Uptime percentage for this period", example: 100 },
			latency_min: { type: "number", description: "Minimum latency in milliseconds", example: 40 },
			latency_max: { type: "number", description: "Maximum latency in milliseconds", example: 65 },
			latency_avg: { type: "number", description: "Average latency in milliseconds", example: 52.3 },
		},
	},
	MonitorHistory: {
		type: "object",
		required: ["monitorId", "type", "data"],
		properties: {
			monitorId: { type: "string", example: "api-prod" },
			type: { type: "string", enum: ["raw", "hourly", "daily"], example: "raw" },
			data: {
				type: "array",
				items: { $ref: "#/components/schemas/HistoryRecord" },
			},
			customMetrics: {
				type: "object",
				description: "Custom metric configurations for this monitor",
				properties: {
					custom1: { $ref: "#/components/schemas/CustomMetricConfig" },
					custom2: { $ref: "#/components/schemas/CustomMetricConfig" },
					custom3: { $ref: "#/components/schemas/CustomMetricConfig" },
				},
			},
		},
	},
	GroupHistory: {
		type: "object",
		required: ["groupId", "type", "data"],
		properties: {
			groupId: { type: "string", example: "production" },
			type: { type: "string", enum: ["raw", "hourly", "daily"], example: "raw" },
			strategy: {
				type: "string",
				enum: ["any-up", "percentage", "all-up"],
				description: "Strategy used for determining group status",
				example: "percentage",
			},
			data: {
				type: "array",
				items: { $ref: "#/components/schemas/HistoryRecord" },
			},
		},
	},
	Incident: {
		type: "object",
		required: ["id", "status_page_id", "title", "status", "severity", "affected_monitors", "created_at", "updated_at"],
		properties: {
			id: { type: "string", example: "a1b2c3d4e5f6a1b2c3d4e5f6" },
			status_page_id: { type: "string", example: "main" },
			title: { type: "string", example: "Database connectivity issues" },
			status: { type: "string", enum: ["investigating", "identified", "monitoring", "resolved"], example: "investigating" },
			severity: { type: "string", enum: ["minor", "major", "critical"], example: "major" },
			affected_monitors: { type: "array", items: { type: "string" }, example: ["api-prod", "web-app"] },
			suppress_notifications: {
				type: "boolean",
				description: "Whether notifications are suppressed for affected monitors during the incident",
				example: true,
			},
			created_at: { type: "string", format: "date-time", example: "2025-06-15T10:30:00.000Z" },
			updated_at: { type: "string", format: "date-time", example: "2025-06-15T11:00:00.000Z" },
			resolved_at: { type: "string", format: "date-time", nullable: true, example: null },
		},
	},
	IncidentUpdate: {
		type: "object",
		required: ["id", "incident_id", "status", "message", "created_at"],
		properties: {
			id: { type: "string", example: "f6e5d4c3b2a1f6e5d4c3b2a1" },
			incident_id: { type: "string", example: "a1b2c3d4e5f6a1b2c3d4e5f6" },
			status: { type: "string", enum: ["investigating", "identified", "monitoring", "resolved"], example: "identified" },
			message: { type: "string", example: "We have identified the root cause as a failed database migration." },
			created_at: { type: "string", format: "date-time", example: "2025-06-15T10:45:00.000Z" },
		},
	},
	IncidentWithUpdates: {
		type: "object",
		required: ["id", "status_page_id", "title", "status", "severity", "affected_monitors", "created_at", "updated_at", "updates"],
		properties: {
			id: { type: "string" },
			status_page_id: { type: "string" },
			title: { type: "string" },
			status: { type: "string", enum: ["investigating", "identified", "monitoring", "resolved"] },
			severity: { type: "string", enum: ["minor", "major", "critical"] },
			affected_monitors: { type: "array", items: { type: "string" } },
			suppress_notifications: {
				type: "boolean",
				description: "Whether notifications are suppressed for affected monitors during the incident",
			},
			created_at: { type: "string", format: "date-time" },
			updated_at: { type: "string", format: "date-time" },
			resolved_at: { type: "string", format: "date-time", nullable: true },
			updates: {
				type: "array",
				items: { $ref: "#/components/schemas/IncidentUpdate" },
				description: "All timeline updates for this incident, ordered chronologically",
			},
		},
	},
	AdminIncidentCreate: {
		type: "object",
		required: ["status_page_id", "title", "status", "severity", "message"],
		properties: {
			status_page_id: { type: "string", description: "ID of the status page this incident belongs to", example: "main" },
			title: { type: "string", description: "Short incident title", example: "Database connectivity issues" },
			status: { type: "string", enum: ["investigating", "identified", "monitoring", "resolved"], example: "investigating" },
			severity: { type: "string", enum: ["minor", "major", "critical"], example: "major" },
			message: {
				type: "string",
				description: "Initial timeline update message",
				example: "We are investigating reports of degraded database performance.",
			},
			affected_monitors: {
				type: "array",
				items: { type: "string" },
				description: "Optional list of affected monitor/group IDs (must be on the status page)",
				example: ["api-prod"],
			},
			suppress_notifications: {
				type: "boolean",
				description: "Whether to suppress notifications for affected monitors during the incident (default: true)",
				default: true,
			},
		},
	},
	AdminIncidentUpdate: {
		type: "object",
		properties: {
			title: { type: "string", example: "Database connectivity issues - resolved" },
			severity: { type: "string", enum: ["minor", "major", "critical"] },
			affected_monitors: { type: "array", items: { type: "string" } },
			suppress_notifications: { type: "boolean", description: "Whether to suppress notifications for affected monitors during the incident" },
		},
	},
	Maintenance: {
		type: "object",
		required: [
			"id",
			"status_page_id",
			"title",
			"status",
			"scheduled_start",
			"scheduled_end",
			"affected_monitors",
			"suppress_notifications",
			"created_at",
			"updated_at",
		],
		properties: {
			id: { type: "string", example: "b2c3d4e5-f6a7-8901-bcde-f12345678901" },
			status_page_id: { type: "string", example: "main" },
			title: { type: "string", example: "Scheduled database migration" },
			status: { type: "string", enum: ["scheduled", "in_progress", "completed", "cancelled"], example: "scheduled" },
			scheduled_start: { type: "string", format: "date-time", example: "2026-03-10T02:00:00.000Z" },
			scheduled_end: { type: "string", format: "date-time", example: "2026-03-10T06:00:00.000Z" },
			affected_monitors: { type: "array", items: { type: "string" }, example: ["api-prod", "web-app"] },
			suppress_notifications: {
				type: "boolean",
				description: "Whether notifications are suppressed for affected monitors during the maintenance",
				example: true,
			},
			created_at: { type: "string", format: "date-time", example: "2026-03-05T14:00:00.000Z" },
			updated_at: { type: "string", format: "date-time", example: "2026-03-05T14:00:00.000Z" },
			completed_at: { type: "string", format: "date-time", nullable: true, example: null },
		},
	},
	MaintenanceUpdate: {
		type: "object",
		required: ["id", "maintenance_id", "status", "message", "created_at"],
		properties: {
			id: { type: "string", example: "c3d4e5f6-a7b8-9012-cdef-123456789012" },
			maintenance_id: { type: "string", example: "b2c3d4e5-f6a7-8901-bcde-f12345678901" },
			status: { type: "string", enum: ["scheduled", "in_progress", "completed", "cancelled"], example: "in_progress" },
			message: { type: "string", example: "Maintenance has started. Database migration is underway." },
			created_at: { type: "string", format: "date-time", example: "2026-03-10T02:00:00.000Z" },
		},
	},
	MaintenanceWithUpdates: {
		type: "object",
		required: [
			"id",
			"status_page_id",
			"title",
			"status",
			"scheduled_start",
			"scheduled_end",
			"affected_monitors",
			"suppress_notifications",
			"created_at",
			"updated_at",
			"updates",
		],
		properties: {
			id: { type: "string" },
			status_page_id: { type: "string" },
			title: { type: "string" },
			status: { type: "string", enum: ["scheduled", "in_progress", "completed", "cancelled"] },
			scheduled_start: { type: "string", format: "date-time" },
			scheduled_end: { type: "string", format: "date-time" },
			affected_monitors: { type: "array", items: { type: "string" } },
			suppress_notifications: { type: "boolean", description: "Whether notifications are suppressed for affected monitors during the maintenance" },
			created_at: { type: "string", format: "date-time" },
			updated_at: { type: "string", format: "date-time" },
			completed_at: { type: "string", format: "date-time", nullable: true },
			updates: {
				type: "array",
				items: { $ref: "#/components/schemas/MaintenanceUpdate" },
				description: "All timeline updates for this maintenance, ordered chronologically",
			},
		},
	},
	AdminMaintenanceCreate: {
		type: "object",
		required: ["status_page_id", "title", "status", "scheduled_start", "scheduled_end", "message"],
		properties: {
			status_page_id: { type: "string", description: "ID of the status page this maintenance belongs to", example: "main" },
			title: { type: "string", description: "Short maintenance title", example: "Scheduled database migration" },
			status: { type: "string", enum: ["scheduled", "in_progress", "completed", "cancelled"], example: "scheduled" },
			scheduled_start: { type: "string", format: "date-time", description: "Scheduled start time (ISO 8601)", example: "2026-03-10T02:00:00.000Z" },
			scheduled_end: {
				type: "string",
				format: "date-time",
				description: "Scheduled end time (ISO 8601, must be after scheduled_start)",
				example: "2026-03-10T06:00:00.000Z",
			},
			message: {
				type: "string",
				description: "Initial timeline update message",
				example: "Database migration scheduled for March 10th, 2:00-6:00 AM UTC.",
			},
			affected_monitors: {
				type: "array",
				items: { type: "string" },
				description: "Optional list of affected monitor/group IDs (must be on the status page)",
				example: ["api-prod"],
			},
			suppress_notifications: {
				type: "boolean",
				description: "Whether to suppress notifications for affected monitors during the maintenance (default: true)",
				default: true,
			},
		},
	},
	AdminMaintenanceUpdate: {
		type: "object",
		properties: {
			title: { type: "string", example: "Scheduled database migration - extended" },
			scheduled_start: { type: "string", format: "date-time", description: "Updated start time (ISO 8601)" },
			scheduled_end: { type: "string", format: "date-time", description: "Updated end time (ISO 8601, must be after scheduled_start)" },
			affected_monitors: { type: "array", items: { type: "string" } },
			suppress_notifications: { type: "boolean", description: "Whether to suppress notifications for affected monitors during the maintenance" },
		},
	},
	AdminSuccess: {
		type: "object",
		required: ["success", "message"],
		properties: {
			success: { type: "boolean", enum: [true] },
			message: { type: "string", example: "Resource updated" },
		},
	},
	AdminSuccessWithId: {
		type: "object",
		required: ["success", "message", "id"],
		properties: {
			success: { type: "boolean", enum: [true] },
			message: { type: "string", example: "Resource created" },
			id: { type: "string", example: "my-resource" },
		},
	},
	AdminValidationError: {
		type: "object",
		required: ["error", "details"],
		properties: {
			error: { type: "string", example: "Validation failed" },
			details: {
				type: "array",
				items: { type: "string" },
				example: ["name is required", "interval must be a positive number"],
			},
		},
	},
	AdminMonitor: {
		type: "object",
		required: ["id", "name", "token", "interval", "maxRetries", "resendNotification", "notificationChannels", "dependencies", "pulseMonitors"],
		properties: {
			id: { type: "string", example: "api-prod" },
			name: { type: "string", example: "Production API" },
			token: { type: "string", example: "tk_prod_api_abc123" },
			interval: { type: "number", description: "Expected pulse interval in seconds", example: 30 },
			maxRetries: { type: "integer", description: "Missed pulses before marking down", example: 0 },
			resendNotification: { type: "integer", description: "Resend notification every N down checks (0 = never)", example: 12 },
			children: { type: "array", items: { type: "string" }, description: "Array of child monitor/group IDs" },
			notificationChannels: { type: "array", items: { type: "string" }, example: ["critical"] },
			dependencies: { type: "array", items: { type: "string" }, example: [] },
			pulseMonitors: { type: "array", items: { type: "string" }, example: [] },
			custom1: { $ref: "#/components/schemas/CustomMetricConfig" },
			custom2: { $ref: "#/components/schemas/CustomMetricConfig" },
			custom3: { $ref: "#/components/schemas/CustomMetricConfig" },
			pulse: {
				type: "object",
				description: "PulseMonitor protocol configuration (omitted if not set)",
			},
		},
	},
	AdminMonitorCreate: {
		type: "object",
		required: ["id", "name", "token", "interval", "maxRetries", "resendNotification"],
		properties: {
			id: { type: "string", description: "Unique ID (alphanumeric, hyphens, underscores)", example: "api-staging" },
			name: { type: "string", example: "Staging API" },
			token: { type: "string", description: "Unique secret token for sending pulses", example: "tk_staging_api_def456" },
			interval: { type: "number", description: "Expected pulse interval in seconds (> 0)", example: 30 },
			maxRetries: { type: "integer", description: "Missed pulses before marking down (>= 0)", minimum: 0, example: 2 },
			resendNotification: { type: "integer", description: "Resend notification every N down checks (0 = never)", minimum: 0, example: 0 },
			children: { type: "array", items: { type: "string" }, description: "Array of child monitor/group IDs" },
			notificationChannels: { type: "array", items: { type: "string" }, description: "Notification channel IDs" },
			dependencies: { type: "array", items: { type: "string" }, description: "Monitor/group IDs for notification suppression" },
			pulseMonitors: { type: "array", items: { type: "string" }, description: "PulseMonitor IDs" },
			custom1: { $ref: "#/components/schemas/CustomMetricConfig" },
			custom2: { $ref: "#/components/schemas/CustomMetricConfig" },
			custom3: { $ref: "#/components/schemas/CustomMetricConfig" },
			pulse: { type: "object", description: "PulseMonitor protocol configuration (http, tcp, etc.)" },
		},
	},
	AdminMonitorUpdate: {
		type: "object",
		properties: {
			name: { type: "string", example: "Staging API v2" },
			token: { type: "string" },
			interval: { type: "number", description: "Must be > 0" },
			maxRetries: { type: "integer", minimum: 0 },
			resendNotification: { type: "integer", minimum: 0 },
			children: { type: "array", items: { type: "string" }, nullable: true, description: "Set to null to remove" },
			notificationChannels: { type: "array", items: { type: "string" } },
			dependencies: { type: "array", items: { type: "string" } },
			pulseMonitors: { type: "array", items: { type: "string" } },
			custom1: { oneOf: [{ $ref: "#/components/schemas/CustomMetricConfig" }, { type: "null" }], description: "Set to null to remove" },
			custom2: { oneOf: [{ $ref: "#/components/schemas/CustomMetricConfig" }, { type: "null" }], description: "Set to null to remove" },
			custom3: { oneOf: [{ $ref: "#/components/schemas/CustomMetricConfig" }, { type: "null" }], description: "Set to null to remove" },
			pulse: { type: "object", nullable: true, description: "Set to null to remove" },
		},
	},
	AdminGroup: {
		type: "object",
		required: ["id", "name", "strategy", "degradedThreshold", "interval", "resendNotification", "notificationChannels", "dependencies"],
		properties: {
			id: { type: "string", example: "production" },
			name: { type: "string", example: "Production Services" },
			strategy: { type: "string", enum: ["any-up", "percentage", "all-up"], example: "percentage" },
			degradedThreshold: { type: "number", description: "Percentage threshold for degraded status (0-100)", minimum: 0, maximum: 100, example: 50 },
			interval: { type: "number", description: "Interval in seconds for uptime calculations", example: 60 },
			resendNotification: { type: "integer", description: "Resend notification every N down checks (0 = never)", example: 12 },
			children: { type: "array", items: { type: "string" }, description: "Array of child monitor/group IDs" },
			notificationChannels: { type: "array", items: { type: "string" }, example: [] },
			dependencies: { type: "array", items: { type: "string" }, example: [] },
		},
	},
	AdminGroupCreate: {
		type: "object",
		required: ["id", "name", "strategy", "degradedThreshold", "interval"],
		properties: {
			id: { type: "string", description: "Unique ID (alphanumeric, hyphens, underscores)", example: "eu-services" },
			name: { type: "string", example: "EU Services" },
			strategy: { type: "string", enum: ["any-up", "percentage", "all-up"], example: "percentage" },
			degradedThreshold: { type: "number", minimum: 0, maximum: 100, example: 50 },
			interval: { type: "number", description: "Must be > 0", example: 60 },
			resendNotification: { type: "integer", minimum: 0, description: "Defaults to 0", example: 0 },
			children: { type: "array", items: { type: "string" }, description: "Array of child monitor/group IDs" },
			notificationChannels: { type: "array", items: { type: "string" } },
			dependencies: { type: "array", items: { type: "string" } },
		},
	},
	AdminGroupUpdate: {
		type: "object",
		properties: {
			name: { type: "string" },
			strategy: { type: "string", enum: ["any-up", "percentage", "all-up"] },
			degradedThreshold: { type: "number", minimum: 0, maximum: 100 },
			interval: { type: "number", description: "Must be > 0" },
			resendNotification: { type: "integer", minimum: 0 },
			children: { type: "array", items: { type: "string" }, nullable: true, description: "Set to null to remove" },
			notificationChannels: { type: "array", items: { type: "string" } },
			dependencies: { type: "array", items: { type: "string" } },
		},
	},
	AdminStatusPage: {
		type: "object",
		required: ["id", "name", "slug", "items"],
		properties: {
			id: { type: "string", example: "public" },
			name: { type: "string", example: "Public Status Page" },
			slug: { type: "string", example: "status" },
			items: { type: "array", items: { type: "string" }, description: "Monitor and/or group IDs", example: ["all-services", "third-party"] },
			leafItems: {
				type: "array",
				items: { type: "string" },
				description: "IDs treated as leaf nodes (children not expanded on status page)",
				example: ["europe"],
			},
			password: { type: "string", description: "Password for protection (omitted if not set)" },
			reports: { type: "boolean", description: "Whether report export endpoints are enabled (default: false)", example: false },
		},
	},
	AdminStatusPageCreate: {
		type: "object",
		required: ["id", "name", "slug", "items"],
		properties: {
			id: { type: "string", description: "Unique ID (alphanumeric, hyphens, underscores)", example: "partners" },
			name: { type: "string", example: "Partner Status" },
			slug: { type: "string", description: "URL slug (lowercase letters, numbers, hyphens only)", example: "partner-status" },
			items: { type: "array", items: { type: "string" }, description: "Non-empty array of monitor/group IDs", example: ["production", "api-prod"] },
			leafItems: { type: "array", items: { type: "string" }, nullable: true, description: "Set to null to remove" },
			password: { type: "string", description: "Password to protect the page (minimum 8 characters)" },
			reports: { type: "boolean", description: "Enable report export endpoints (default: false)" },
		},
	},
	AdminStatusPageUpdate: {
		type: "object",
		properties: {
			name: { type: "string" },
			slug: { type: "string", description: "Must not conflict with another status page" },
			items: { type: "array", items: { type: "string" }, description: "Must be non-empty" },
			password: { type: "string", nullable: true, description: "Set to null to remove password protection (minimum 8 characters if set)" },
			reports: { type: "boolean", description: "Enable or disable report export endpoints" },
		},
	},
	AdminNotificationChannel: {
		type: "object",
		required: ["id", "name", "enabled"],
		properties: {
			id: { type: "string", example: "critical" },
			name: { type: "string", example: "Critical Production Alerts" },
			description: { type: "string", description: "Omitted if not set", example: "High-priority alerts" },
			enabled: { type: "boolean", example: true },
			discord: { $ref: "#/components/schemas/AdminDiscordConfig" },
			email: { $ref: "#/components/schemas/AdminEmailConfig" },
			ntfy: { $ref: "#/components/schemas/AdminNtfyConfig" },
			telegram: { $ref: "#/components/schemas/AdminTelegramConfig" },
			webhook: { $ref: "#/components/schemas/AdminWebhookConfig" },
		},
	},
	AdminNotificationChannelCreate: {
		type: "object",
		required: ["id", "name", "enabled"],
		properties: {
			id: { type: "string", description: "Unique ID (alphanumeric, hyphens, underscores)", example: "ops-alerts" },
			name: { type: "string", example: "Ops Team Alerts" },
			description: { type: "string" },
			enabled: { type: "boolean", example: true },
			discord: { $ref: "#/components/schemas/AdminDiscordConfig" },
			email: { $ref: "#/components/schemas/AdminEmailConfig" },
			ntfy: { $ref: "#/components/schemas/AdminNtfyConfig" },
			telegram: { $ref: "#/components/schemas/AdminTelegramConfig" },
			webhook: { $ref: "#/components/schemas/AdminWebhookConfig" },
		},
	},
	AdminNotificationChannelUpdate: {
		type: "object",
		properties: {
			name: { type: "string" },
			description: { type: "string", nullable: true },
			enabled: { type: "boolean" },
			discord: { oneOf: [{ $ref: "#/components/schemas/AdminDiscordConfig" }, { type: "null" }], description: "Set to null to remove" },
			email: { oneOf: [{ $ref: "#/components/schemas/AdminEmailConfig" }, { type: "null" }], description: "Set to null to remove" },
			ntfy: { oneOf: [{ $ref: "#/components/schemas/AdminNtfyConfig" }, { type: "null" }], description: "Set to null to remove" },
			telegram: { oneOf: [{ $ref: "#/components/schemas/AdminTelegramConfig" }, { type: "null" }], description: "Set to null to remove" },
			webhook: { oneOf: [{ $ref: "#/components/schemas/AdminWebhookConfig" }, { type: "null" }], description: "Set to null to remove" },
		},
	},
	AdminDiscordConfig: {
		type: "object",
		required: ["enabled"],
		properties: {
			enabled: { type: "boolean", example: true },
			webhookUrl: { type: "string", description: "Required when enabled", example: "https://discord.com/api/webhooks/123/abc" },
			username: { type: "string", example: "Alert Bot" },
			avatarUrl: { type: "string", example: "https://example.com/avatar.png" },
			mentions: {
				type: "object",
				properties: {
					users: { type: "array", items: { type: "string" }, description: "Discord user IDs" },
					roles: { type: "array", items: { type: "string" }, description: "Discord role IDs" },
					everyone: { type: "boolean" },
				},
			},
		},
	},
	AdminEmailConfig: {
		type: "object",
		required: ["enabled"],
		properties: {
			enabled: { type: "boolean", example: true },
			from: { type: "string", description: "Sender address (required when enabled)", example: '"Uptime Monitor" <alerts@example.com>' },
			to: { type: "array", items: { type: "string" }, description: "Recipient addresses (required when enabled)", example: ["admin@example.com"] },
			smtp: {
				type: "object",
				description: "SMTP configuration (required when enabled)",
				required: ["host", "port", "secure", "user", "pass"],
				properties: {
					host: { type: "string", example: "smtp.example.com" },
					port: { type: "integer", example: 465 },
					secure: { type: "boolean", example: true },
					user: { type: "string", example: "alerts@example.com" },
					pass: { type: "string", example: "your-smtp-password" },
				},
			},
		},
	},
	AdminNtfyConfig: {
		type: "object",
		required: ["enabled"],
		properties: {
			enabled: { type: "boolean", example: true },
			server: { type: "string", description: "Required when enabled", example: "https://ntfy.sh" },
			topic: { type: "string", description: "Required when enabled", example: "uptime-monitor" },
			token: { type: "string", description: "Optional token authentication" },
			username: { type: "string", description: "Optional username (must be paired with password)" },
			password: { type: "string", description: "Optional password (must be paired with username)" },
		},
	},
	AdminTelegramConfig: {
		type: "object",
		required: ["enabled"],
		properties: {
			enabled: { type: "boolean", example: true },
			botToken: { type: "string", description: "Required when enabled", example: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11" },
			chatId: { type: "string", description: "Required when enabled", example: "-1001234567890" },
			topicId: { type: "integer", description: "Optional forum topic ID" },
			disableNotification: { type: "boolean", description: "Send silently" },
		},
	},
	AdminWebhookConfig: {
		type: "object",
		required: ["enabled"],
		properties: {
			enabled: { type: "boolean", example: true },
			url: { type: "string", description: "Required when enabled", example: "https://example.com/webhook" },
			headers: {
				type: "object",
				additionalProperties: { type: "string" },
				description: "Custom HTTP headers for authentication",
				example: { Authorization: "Bearer your-token" },
			},
		},
	},
	AdminPulseMonitor: {
		type: "object",
		required: ["id", "name", "token"],
		properties: {
			id: { type: "string", example: "US-WEST-1" },
			name: { type: "string", example: "US West 1 (Oregon)" },
			token: { type: "string", example: "tk_pulse_monitor_us_west_1" },
		},
	},
	AdminPulseMonitorCreate: {
		type: "object",
		required: ["id", "name", "token"],
		properties: {
			id: { type: "string", description: "Unique ID (alphanumeric, hyphens, underscores)", example: "AP-EAST-1" },
			name: { type: "string", example: "Asia Pacific (Tokyo)" },
			token: { type: "string", description: "Unique token for WebSocket authentication", example: "tk_pulse_monitor_ap_east_1" },
		},
	},
	AdminPulseMonitorUpdate: {
		type: "object",
		properties: {
			name: { type: "string" },
			token: { type: "string", description: "Must not conflict with another PulseMonitor" },
		},
	},
} as const;
